idf_component_register(
    SRCS
        "hello.cpp"
        "Adafruit_ST7789.cpp"
        "Adafruit_ST77xx.cpp"
        "qrcode_st7789.cpp"
    INCLUDE_DIRS
        "."
        "../lib/QRcodeDisplay/src"
        "../lib/PubSubClient/src"
        "../lib/Adafruit_GFX_Library"
        "../lib/Adafruit_BusIO"
    REQUIRES
        arduino
        Adafruit_BusIO
        Adafruit_GFX_Library
        PubSubClient
        QRcodeDisplay
        mbedtls
)